"use client";
import { useState,useEffect } from "react";
import { ArrowRight,KeyRound,LockKeyhole,ShieldCheck,Download,Copy,LogOut } from "lucide-react";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { api,errorMessage } from "@/lib/client";
import { ErrorNote } from "./common";

export function RecoveryNotice({code,onDone}:{code:string;onDone:()=>void}){
 function download(){const blob=new Blob(["C KI KA LA — code de récupération\n\n"+code+"\n\nConserve ce code dans un gestionnaire de mots de passe. Il remplace ton mot de passe si tu l’oublies. Ne le communique à personne. Après utilisation ou renouvellement, il devient invalide.\n"],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="c-ki-ka-la-code-de-recuperation.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel recovery-notice" role="status"><KeyRound size={28}/><h2>Garde ta clé de secours.</h2><p>Ce code permet de récupérer ton compte si tu oublies ton mot de passe. Il ne sera plus affiché ensuite.</p><code>{code}</code><div className="row"><button className="button secondary" onClick={download}><Download size={16}/>Télécharger</button><button className="button ghost" onClick={async()=>{try{await navigator.clipboard.writeText(code);toast.success("Code copié.");}catch{toast.error("Sélectionne le code pour le copier.");}}}><Copy size={16}/>Copier</button></div><p className="help-note">Conserve-le dans un endroit privé. Un nouveau code invalide le précédent.</p><button className="button primary wide mt" onClick={onDone}>J’ai conservé mon code<ArrowRight size={16}/></button></section>;
}
export function AuthPanel({onRefresh,activation=false}:{onRefresh:()=>Promise<void>;activation?:boolean}){
 const [mode,setMode]=useState("login");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [code,setCode]=useState("");const [recoveryCode,setRecoveryCode]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(!activation&&new URLSearchParams(window.location.search).get("mode")==="register")setMode("register");},[activation]);
 const register=mode==="register"||activation;const recovering=mode==="recover"&&!activation;
 if(recoveryCode)return <RecoveryNotice code={recoveryCode} onDone={async()=>{setRecoveryCode("");setPassword("");setConfirm("");setCode("");if(recovering){setMode("login");toast.success("Mot de passe remplacé. Connecte-toi.");}else{await onRefresh();if(activation)window.location.href="/admin";}}}/>;
 return <section className="panel auth-panel"><div className="eyebrow">{activation?<ShieldCheck size={16}/>:<LockKeyhole size={16}/>}{activation?"ACCÈS PROPRIÉTAIRE":"TON COMPTE C KI KA LA"}</div><h2>{activation?"Active ton administration.":recovering?"Retrouve ta place.":"Le même pseudo. Toute ton histoire."}</h2><p className="muted mt">{activation?"L’adresse du propriétaire et son code privé sont nécessaires. Choisis ton propre mot de passe.":"Tes parties, tes sets et tes statistiques te suivent sur tous tes appareils."}</p>
 {!activation&&!recovering&&<Tabs value={mode} onValueChange={v=>{setMode(v);setError("");}} className="mt"><TabsList className="auth-tabs"><TabsTrigger value="login">Connexion</TabsTrigger><TabsTrigger value="register">Créer un compte</TabsTrigger></TabsList></Tabs>}
 <form className="mt" onSubmit={async e=>{e.preventDefault();setError("");if((register||recovering)&&password!==confirm){setError("Les deux mots de passe ne correspondent pas.");return;}setBusy(true);try{
  const path=activation?"activate-owner":recovering?"recover":register?"sign-up/email":"sign-in/email";
  const body=activation?{name,email,password,setupCode:code}:recovering?{email,code,newPassword:password}:register?{name,email,password}:{email,password};
  const result=await api("auth/"+path,"POST",body);setPassword("");setConfirm("");
  if(result.recoveryCode)setRecoveryCode(result.recoveryCode);else{await onRefresh();toast.success("Te voilà connecté.");}
 }catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>
 {register&&<label className="field">Ton pseudo<input autoComplete="nickname" required minLength={2} maxLength={24} value={name} onChange={e=>setName(e.target.value)}/></label>}
 <label className="field">Adresse e-mail<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>
 {(activation||recovering)&&<label className="field">{activation?"Code privé d’activation":"Code de récupération"}<input type="password" required autoComplete="off" maxLength={100} value={code} onChange={e=>setCode(e.target.value)}/></label>}
 <label className="field">{recovering?"Nouveau mot de passe":"Mot de passe"}<input type="password" required minLength={register||recovering?12:1} maxLength={128} autoComplete={register||recovering?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>
 {(register||recovering)&&<><label className="field">Confirme le mot de passe<input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="help-note">Au moins 12 caractères. Une phrase longue est plus facile à retenir.</p></>}
 <ErrorNote error={error}/><button className="button primary wide mt" disabled={busy}>{busy?"Un instant…":activation?"Activer mon compte administrateur":recovering?"Remplacer mon mot de passe":register?"Créer mon compte":"Me connecter"}<ArrowRight size={17}/></button>
 </form>{!activation&&<div className="auth-links"><button className="textlink" onClick={()=>{setMode(recovering?"login":"recover");setError("");}}>{recovering?"Retour à la connexion":"Mot de passe oublié ?"}</button><a className="textlink" href="/">Jouer en invité</a></div>}
 {recovering&&<p className="help-note mt">Utilise le code remis lors de ton inscription. La récupération par e-mail n’est pas encore activée.</p>}
 <p className="help-note mt">Ton e-mail reste privé. <a className="textlink" href="/privacy">Données et confidentialité</a></p></section>;
}
export function SecurityPanel({onRefresh}:{onRefresh:()=>Promise<void>}){
 const [current,setCurrent]=useState("");const [next,setNext]=useState("");const [confirm,setConfirm]=useState("");const [recovery,setRecovery]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function act(path:string,body:unknown){setBusy(true);setError("");try{const result=await api("auth/"+path,"POST",body);setCurrent("");setNext("");setConfirm("");if(result.recoveryCode)setRecovery(result.recoveryCode);else toast.success("Sécurité du compte mise à jour.");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 if(recovery)return <div className="mt"><RecoveryNotice code={recovery} onDone={()=>setRecovery("")}/></div>;
 return <section className="panel mt"><h2>Protège ton compte.</h2><p className="help-note mt">Le mot de passe actuel est nécessaire pour le remplacer ou renouveler ton code de secours.</p><div className="form-two mt"><label className="field">Mot de passe actuel<input type="password" autoComplete="current-password" maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/></label><div/></div><form onSubmit={e=>{e.preventDefault();if(next!==confirm){setError("Les deux mots de passe ne correspondent pas.");return;}void act("change-password",{currentPassword:current,newPassword:next});}}><div className="form-two"><label className="field">Nouveau mot de passe<input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></label><label className="field">Confirme le nouveau mot de passe<input type="password" required minLength={12} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></div><button className="button secondary" disabled={busy||!current}>Changer mon mot de passe</button></form><div className="row mt"><button className="button secondary" disabled={busy||!current} onClick={()=>void act("rotate-recovery",{password:current})}><KeyRound size={16}/>Nouveau code de secours</button><button className="button ghost" disabled={busy} onClick={()=>void act("revoke-other-sessions",{})}>Déconnecter mes autres appareils</button><button className="button ghost" disabled={busy} onClick={async()=>{try{await api("auth/sign-out","POST");await onRefresh();}catch(e){setError(errorMessage(e));}}}><LogOut size={16}/>Déconnexion</button></div><ErrorNote error={error}/></section>;
}
