"use client";
import { useState,type CSSProperties } from "react";
import { Check,CheckCheck,GripVertical,LoaderCircle,Undo2 } from "lucide-react";
import { toast } from "sonner";
import { TIERS,scoreTier,type Target,type Ranking } from "@/lib/game-data";
import { Avatar } from "./common";

export function TierBuilder({targets,onSubmit,busy}:{targets:Target[];onSubmit:(rankings:Ranking)=>Promise<unknown>;busy:boolean}){
 const [rankings,setRankings]=useState<Ranking>({});const [selected,setSelected]=useState<string|null>(null);const [over,setOver]=useState<number|null>(null);
 const pending=targets.filter(t=>rankings[t.id]===undefined),omitted=targets.filter(t=>rankings[t.id]===null);
 const ranked=targets.filter(t=>typeof rankings[t.id]==="number").length;
 const selectedTarget=targets.find(t=>t.id===selected);
 function place(id:string,value:number|null){if(busy||!targets.some(t=>t.id===id))return;setRankings(r=>({...r,[id]:value}));setSelected(null);setOver(null);}
 function chip(t:Target){const value=rankings[t.id];return <button key={t.id} type="button" className={"player-chip"+(selected===t.id?" selected":"")} draggable={!busy} disabled={busy} aria-pressed={selected===t.id} aria-label={t.name+", "+(value===undefined?"à classer":value===null?"non classé":"rang "+scoreTier(value).key)} onClick={()=>setSelected(s=>s===t.id?null:t.id)} onKeyDown={e=>{if(e.key==="Escape")setSelected(null);}} onDragStart={e=>{e.dataTransfer.setData("text/plain",t.id);e.dataTransfer.effectAllowed="move";setSelected(t.id);}} onDragEnd={()=>{setOver(null);setSelected(null);}}><GripVertical size={14} className="drag-grip"/><Avatar {...t}/><span className="chip-name">{t.name}</span></button>;}
 return <><section className="bench"><div className="bench-header"><span className="touch-help">Touche un nom, puis un rang.</span><span className="pointer-help">Glisse un nom dans un rang, ou clique sur les deux.</span><span>{ranked} classés · {omitted.length} non classés</span></div><div className="bench-players">{pending.length?pending.map(chip):<span className="row help-note"><CheckCheck size={16}/>Tous les choix sont faits. Tu peux encore les modifier.</span>}</div></section>
 <div className="selection-bar" aria-live="polite"><span>{selectedTarget?<><b>{selectedTarget.name}</b> : choisis un rang ou « Non classé ».</>:"S correspond beaucoup à la question, E pas du tout."}</span>{selected&&<button className="button ghost small" onClick={()=>{setRankings(r=>{const next={...r};delete next[selected];return next;});setSelected(null);}} disabled={busy}><Undo2 size={15}/>Remettre à choisir</button>}</div>
 <div className="tier-board" aria-label="Ta tier list">{TIERS.map(t=><div key={t.key} className={"tier-row"+(over===t.value?" target":"")} style={{"--tier":t.color} as CSSProperties} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";setOver(t.value);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null))setOver(null);}} onDrop={e=>{e.preventDefault();e.stopPropagation();place(e.dataTransfer.getData("text/plain"),t.value);}}><button type="button" className="tier-label" disabled={busy} aria-label={"Placer dans le rang "+t.key} onClick={()=>{if(selected)place(selected,t.value);else toast("Sélectionne d’abord un nom à classer.");}}><strong>{t.key}</strong><small>{t.label}</small></button><div className="tier-content" onClick={e=>{if(e.target===e.currentTarget&&selected)place(selected,t.value);}}>{targets.filter(p=>rankings[p.id]===t.value).map(chip)}{!targets.some(p=>rankings[p.id]===t.value)&&<span className="tier-hint" onClick={()=>{if(selected)place(selected,t.value);}}>{selected?"Placer ici":"—"}</span>}</div></div>)}</div>
 <section className="unranked-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(e.dataTransfer.getData("text/plain"),null);}}><div className="section-head"><div><h3>Non classé</h3><p className="help-note">Pas d’avis ? Aucun point, aucun E.</p></div><button className="button secondary small" disabled={busy||!selected} onClick={()=>{if(selected)place(selected,null);}}>Ne pas classer{selectedTarget?" "+selectedTarget.name:""}</button></div><div className="bench-players">{omitted.map(chip)}</div>{pending.length>0&&<button className="textlink" disabled={busy} onClick={()=>{setRankings(r=>({...r,...Object.fromEntries(pending.map(t=>[t.id,null]))}));setSelected(null);}}>Laisser les {pending.length} noms restants non classés</button>}</section>
 <div className="board-footer"><p className="help-note">{pending.length?pending.length+" choix à terminer.":ranked===0?"Classe au moins un nom pour envoyer un classement.":"Prêt à envoyer. Les votes seront visibles dans la salle à la révélation."} Plusieurs noms peuvent partager un rang.</p><button className="button primary" disabled={pending.length>0||ranked===0||busy} onClick={()=>void onSubmit(rankings)}>{busy?<LoaderCircle size={17} className="spinner"/>:<Check size={17}/>}Valider ma tier list</button></div></>;
}
