// Server-only question bank: public catalogue exposes three samples per pack.
export const PREMIUM_QUESTIONS:Record<string,readonly string[]>={
 anime:[
 "Qui ferait le discours le plus long avant un combat ?","Qui aurait un pouvoir incroyable mais oublierait comment l’utiliser ?","Qui recruterait le méchant dans son équipe ?","Qui raterait l’entraînement pour aller manger ?","Qui serait le personnage mystérieux du premier épisode ?","Qui raconterait toute son enfance pendant un duel ?","Qui sacrifierait son goûter pour sauver le groupe ?","Qui aurait la transformation la plus dramatique ?","Qui ferait semblant de ne pas être impressionné ?","Qui deviendrait le rival pour une histoire de dessert ?","Qui nommerait toutes ses attaques ?","Qui se perdrait en allant au tournoi ?","Qui cacherait son vrai niveau jusqu’au dernier moment ?","Qui collectionnerait des objets sans comprendre leur pouvoir ?","Qui se lierait d’amitié avec la créature la plus étrange ?","Qui transformerait une corvée en arc d’entraînement ?","Qui inventerait une technique interdite totalement inutile ?","Qui changerait de camp pour un meilleur uniforme ?","Qui ferait le meilleur capitaine d’équipage ?","Qui ferait un récapitulatif de vingt minutes avant la suite ?"
 ],
 campus:[
 "Qui transformerait un travail de groupe en réunion de crise ?","Qui découvrirait la date du rendu la veille ?","Qui ferait une présentation sans ouvrir ses notes ?","Qui connaîtrait tout le monde dès la rentrée ?","Qui lancerait une association pour une idée absurde ?","Qui réserverait une salle pour finalement travailler au café ?","Qui aurait le sac le mieux préparé pour une journée de cours ?","Qui poserait la dernière question alors que tout le monde part ?","Qui trouverait le meilleur endroit pour une sieste ?","Qui improviserait le meilleur exposé sur un sujet inconnu ?","Qui organiserait la soirée puis partirait en premier ?","Qui serait élu délégué sans l’avoir demandé ?","Qui prêterait ses fiches à toute la promo ?","Qui oublierait le nom du cours où il se trouve ?","Qui défendrait une réponse fausse avec beaucoup d’assurance ?","Qui arriverait avec un repas digne d’un restaurant ?","Qui ferait la meilleure affiche pour un événement ?","Qui motiverait le groupe à finir avant minuit ?","Qui se tromperait de bâtiment le jour de l’examen ?","Qui deviendrait la légende du campus pour une raison improbable ?"
 ],
 apocalypse:[
 "Qui négocierait avec les extraterrestres ?","Qui emporterait une enceinte au lieu d’une lampe ?","Qui saurait réparer le véhicule du groupe ?","Qui garderait son calme quand le plan échoue ?","Qui stockerait uniquement ses snacks préférés ?","Qui instaurerait un règlement dès le premier jour ?","Qui voudrait explorer le bruit étrange dehors ?","Qui organiserait un tournoi dans l’abri ?","Qui se ferait ami avec un robot hostile ?","Qui aurait pensé à prendre une trousse de secours ?","Qui raconterait des blagues pendant la fuite ?","Qui proposerait un raccourci beaucoup trop risqué ?","Qui construirait le refuge le plus confortable ?","Qui apprendrait le plus vite à cultiver quelque chose ?","Qui oublierait de charger la dernière batterie ?","Qui tenterait de sauver son canapé ?","Qui deviendrait porte-parole du groupe ?","Qui trouverait encore le moyen d’être en retard ?","Qui ferait le meilleur éclaireur ?","Qui réussirait à faire rire tout le monde au pire moment ?"
 ],
 redflags:[
 "Qui dirait qu’il n’est pas jaloux en posant douze questions ?","Qui analyserait un message avec tout le groupe ?","Qui proposerait un rendez-vous sans choisir le lieu ?","Qui tomberait sous le charme d’une bonne playlist ?","Qui annulerait un plan pour regarder un dernier épisode ?","Qui enverrait trois vocaux pour dire bonjour ?","Qui oublierait qu’il a déjà raconté la même anecdote ?","Qui aurait une liste de critères beaucoup trop précise ?","Qui demanderait conseil puis ferait exactement l’inverse ?","Qui ferait semblant d’aimer un plat pour faire bonne impression ?","Qui chercherait un sens caché dans un simple emoji ?","Qui préparerait la meilleure surprise avec le plus petit budget ?","Qui ferait une blague au moment le moins romantique ?","Qui choisirait un film pendant une heure ?","Qui transformerait un petit désaccord en débat philosophique ?","Qui donnerait un surnom après dix minutes ?","Qui ferait le meilleur premier pas ?","Qui oublierait le monde en racontant sa passion ?","Qui rédigerait puis effacerait le même message vingt fois ?","Qui ferait rire la personne la plus difficile à séduire ?"
 ]
};
