import { z } from "zod";
import { identity } from "./auth";
import { guestCookieName,sessionScope } from "./session-scope";
import { authRoute,ensureGameProfile,requirePassword } from "./auth-routes";
import { adminRoute } from "./admin-server";
import { database } from "./server-db";
import { squadsRoute,squadMembership,squadRoomInfo } from "./squads-server";
import { decksRoute } from "./decks-server";
import { withLock } from "./account-context";
import { billingRoute,rights,requireRoomRights,cancelAccountSubscriptions,billingStatus } from "./billing-server";
import { PREMIUM_QUESTIONS } from "./premium-content";
import { playerStats } from "./player-stats";
import { limitedJson } from "./server-security";
import { PACKS, getPack, type Target, type RoomState, type Person } from "./game-data";
import { GameError, validateBallot, aggregate, shuffle } from "./game-engine";
type Row=Record<string,any>;
type Ctx={request:Request;db:D1Database;setCookie?:string};
const DAY=86400000;
const nameSchema=z.string().trim().min(2,"Le pseudo doit contenir au moins 2 caractères.").max(24,"Maximum 24 caractères.").regex(/^[\p{L}\p{N} ._'’!?-]+$/u,"Utilise des lettres, chiffres, espaces ou tirets.");
const questionSchema=z.string().trim().min(6).max(160).regex(/^[^<>\x00-\x1f\x7f]+$/u);
const itemsSchema=z.array(nameSchema).min(2).max(12).refine(a=>new Set(a.map(n=>n.toLocaleLowerCase("fr"))).size===a.length,"Les éléments doivent avoir des noms distincts.");
const roomSchema=z.object({pack:z.string().refine(v=>PACKS.some(p=>p.id===v),"Pack inconnu"),roundCount:z.union([z.literal(1),z.literal(3),z.literal(5),z.literal(10),z.literal(15)]),duration:z.union([z.literal(45),z.literal(60),z.literal(90),z.literal(120)]),mode:z.enum(["players","set"]).default("players"),squadId:z.string().uuid().optional(),deckId:z.string().uuid().optional(),visualTheme:z.enum(["neon","aurora","sunset"]).default("neon"),themeMode:z.enum(["pack","manual","box","deck"]).default("pack"),question:questionSchema.optional(),setName:nameSchema.optional(),items:itemsSchema.optional()}).strict();
const person=(p:Row):Person=>({id:p.id,name:p.name,avatar:p.avatar,isAccount:!!p.account_id,role:p.role??"player"});
const one=<T=Row>(c:Ctx,sql:string,...a:any[])=>c.db.prepare(sql).bind(...a).first<T>();
const all=async<T=Row>(c:Ctx,sql:string,...a:any[])=> (await c.db.prepare(sql).bind(...a).all<T>()).results;
const run=(c:Ctx,sql:string,...a:any[])=>c.db.prepare(sql).bind(...a).run();
const stmt=(c:Ctx,sql:string,...a:any[])=>c.db.prepare(sql).bind(...a);
const id=()=>crypto.randomUUID();
async function hash(value:string){const raw=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(raw),b=>b.toString(16).padStart(2,"0")).join("");}
const cookieName=guestCookieName;
function cookieToken(c:Ctx){const key=cookieName(c.request);return c.request.headers.get("cookie")?.split(";").map(s=>s.trim()).find(s=>s.startsWith(key+"="))?.slice(key.length+1);}
async function guest(c:Ctx){const token=cookieToken(c);if(!token||!/^[a-f0-9]{64}$/.test(token))return null;return one(c,"SELECT p.* FROM profiles p JOIN guest_sessions s ON p.id=s.profile_id WHERE s.token_hash=? AND s.expires_at>? AND p.auth_subject IS NULL AND p.account_id IS NULL",await hash(token),Date.now());}
async function who(c:Ctx,required=true){const auth=await identity(c.request);let p:Row|null=null;if(auth)p=await one(c,"SELECT * FROM profiles WHERE account_id=?",auth.id);if(!p&&!auth)p=await guest(c);if(p?.suspended_at)throw new GameError(403,"Ce compte est suspendu.");if(!p&&required)throw new GameError(401,"Choisis un pseudo pour continuer.");return p;}
async function requireAccount(c:Ctx){const auth=await identity(c.request);if(!auth)throw new GameError(401,"Connecte-toi pour retrouver ton compte.");const p=await one(c,"SELECT * FROM profiles WHERE account_id=?",auth.id);if(!p)throw new GameError(401,"Crée ton profil pour continuer.");if(p.suspended_at)throw new GameError(403,"Ce compte est suspendu.");return p;}
async function rate(c:Ctx,key:string,max:number,window=60000){const now=Date.now();const row=await one(c,"INSERT INTO rate_limits(key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<=? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<=? THEN excluded.expires_at ELSE expires_at END RETURNING count",key,now+window,now,now);if(row&&row.count>max)throw new GameError(429,"Un peu trop d’actions. Réessaie dans une minute.");}
const readBody=(c:Ctx)=>limitedJson(c.request);
function guard(c:Ctx){const origin=c.request.headers.get("origin");if(origin!==new URL(c.request.url).origin)throw new GameError(403,"Cette action doit être effectuée depuis le jeu.");const site=c.request.headers.get("sec-fetch-site");if(site&&site!=="same-origin"&&site!=="none")throw new GameError(403,"Origine non autorisée.");if(c.request.headers.get("x-ckk-request")!=="1")throw new GameError(403,"Rouvre la page pour continuer.");}
async function cleanup(c:Ctx){const now=Date.now();await c.db.batch([stmt(c,"DELETE FROM rate_limits WHERE key IN (SELECT key FROM rate_limits WHERE expires_at<? LIMIT 100)",now),stmt(c,"DELETE FROM guest_sessions WHERE token_hash IN (SELECT token_hash FROM guest_sessions WHERE expires_at<? LIMIT 50)",now),stmt(c,"DELETE FROM rooms WHERE code IN (SELECT code FROM rooms WHERE expires_at<? LIMIT 10)",now),stmt(c,"DELETE FROM profiles WHERE id IN (SELECT id FROM profiles WHERE auth_subject IS NULL AND account_id IS NULL AND created_at<? AND NOT EXISTS(SELECT 1 FROM guest_sessions s WHERE s.profile_id=profiles.id) AND NOT EXISTS(SELECT 1 FROM members m WHERE m.profile_id=profiles.id) LIMIT 20)",now-30*DAY)]);}
async function profile(c:Ctx,body:unknown){const data=z.object({name:nameSchema,avatar:z.number().int().min(0).max(7).default(0)}).strict().parse(body);const auth=await identity(c.request);let p=await who(c,false);
 if(auth){await ensureGameProfile(auth,c.request,false);p=await one(c,"SELECT * FROM profiles WHERE account_id=?",auth.id);
 }else if(!p){const pid=id();const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join("");await c.db.batch([stmt(c,"INSERT INTO profiles(id,name,avatar,created_at) VALUES(?,?,?,?)",pid,data.name,data.avatar,Date.now()),stmt(c,"INSERT INTO guest_sessions(token_hash,profile_id,expires_at) VALUES(?,?,?)",await hash(token),pid,Date.now()+30*DAY)]);c.setCookie=cookieName(c.request)+"="+token+"; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000"+(new URL(c.request.url).protocol==="https:"?"; Secure":"");p=await one(c,"SELECT * FROM profiles WHERE id=?",pid);}
 if(!p)throw new Error("Profile creation failed");await run(c,"UPDATE profiles SET name=?,avatar=? WHERE id=?",data.name,data.avatar,p.id);return {profile:person({...p,...data})};
}
async function membership(c:Ctx,code:string,requiredActive=false){if(!/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$/.test(code))throw new GameError(404,"Cette salle n’est pas disponible.");const p=await who(c);const room=await one(c,"SELECT * FROM rooms WHERE code=? AND expires_at>?",code,Date.now());const member=await one(c,"SELECT * FROM members WHERE room_code=? AND profile_id=? AND state!='kicked'",code,p!.id);if(!room||!member||(requiredActive&&member.state!=="joined"))throw new GameError(403,"Rejoins cette salle pour y accéder.");return {p:p!,room,member};}
async function createRoom(c:Ctx,body:unknown,sourceCode?:string,copiedDeck?:{name:string;questions:string[]}){const p=await who(c);const data=roomSchema.parse(body);await rate(c,"create:"+p!.id,12,600000);await cleanup(c);const count=await one(c,"SELECT COUNT(*) AS n FROM rooms WHERE host_id=? AND status NOT IN ('finished','closed') AND created_at>?",p!.id,Date.now()-DAY);if(count!.n>=3)throw new GameError(409,"Tu as déjà trois salles ouvertes. Termine ou quitte l’une d’elles.");if(data.mode==="set"&&!data.items)throw new GameError(400,"Ajoute au moins deux éléments au set.");if(data.themeMode==="manual"&&!data.question)throw new GameError(400,"Écris la question de cette manche.");
 await requireRoomRights(p!.id,data.themeMode==="pack"?data.pack:"classique",data.visualTheme);
 if(data.squadId&&!await squadMembership(data.squadId,p!.id))throw new GameError(403,"Rejoins cette Squad pour lui associer une partie.");
 let deck=copiedDeck;
 if(data.themeMode==="deck"&&!deck){if(!p!.account_id||!data.deckId)throw new GameError(400,"Choisis un deck de ton compte.");const saved=await one(c,"SELECT name,questions FROM question_decks WHERE id=? AND owner_id=?",data.deckId,p!.id);if(!saved)throw new GameError(404,"Deck introuvable.");deck={name:saved.name,questions:JSON.parse(saved.questions)};}
 const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let code="";for(let attempt=0;attempt<4;attempt++){code=Array.from(crypto.getRandomValues(new Uint8Array(6)),v=>chars[v%chars.length]).join("");if(!await one(c,"SELECT code FROM rooms WHERE code=?",code))break;if(attempt===3)throw new GameError(503,"Réessaie de créer la salle.");}
 const n=data.themeMode==="manual"?1:deck?Math.min(data.roundCount,deck.questions.length):data.roundCount;const mid=id();const targets=data.mode==="set"?data.items!.map((name,i)=>({id:id(),name,avatar:i%8})):[];const questions=shuffle(deck?.questions??PREMIUM_QUESTIONS[data.pack]??getPack(data.pack).questions);const now=Date.now();const statements=[stmt(c,"INSERT INTO rooms(code,host_id,pack,round_count,duration,mode,theme_mode,set_name,targets,created_at,expires_at,squad_id,deck_name,visual_theme) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",code,p!.id,data.pack,n,data.duration,data.mode,data.themeMode,data.mode==="set"?(data.setName??"Mon set"):"Les joueurs",JSON.stringify(targets),now,now+365*DAY,data.squadId??null,deck?.name??null,data.visualTheme),stmt(c,"INSERT INTO members(id,room_code,profile_id,name,name_key,avatar,last_seen,joined_at) VALUES(?,?,?,?,?,?,?,?)",mid,code,p!.id,p!.name,p!.name.toLocaleLowerCase("fr"),p!.avatar,now,now)];for(let i=1;i<=n;i++)statements.push(stmt(c,"INSERT INTO rounds(room_code,number,question) VALUES(?,?,?)",code,i,data.themeMode==="box"?null:data.themeMode==="manual"?data.question!:questions[i-1]));if(sourceCode)statements.push(stmt(c,"INSERT INTO rematches(source_code,target_code,created_at) VALUES(?,?,?)",sourceCode,code,now));
 await c.db.batch(statements);return {code};
}
/** A rematch creates a fresh lobby; each player opts in with their existing identity. */
async function rematch(c:Ctx,code:string){
 const {room,member,p}=await membership(c,code);
 if(room.status!=="finished"||!JSON.parse(room.roster).includes(member.id))throw new GameError(409,"Termine la partie avant de demander une revanche.");
 await rate(c,"rematch:"+p.id,12,60000);
 const existing=()=>one(c,"SELECT target_code AS code FROM rematches WHERE source_code=?",code);
 const enter=async(target:string)=>{await join(c,target);return {code:target};};
 const prior=await existing();if(prior)return enter(prior.code);
 const question=room.theme_mode==="manual"?await one(c,"SELECT question FROM rounds WHERE room_code=? AND number=1",code):null;
 const config={visualTheme:room.visual_theme,...(room.squad_id&&await squadMembership(room.squad_id,p.id)?{squadId:room.squad_id}:{}),pack:room.pack,roundCount:[1,3,5,10,15].includes(room.round_count)?room.round_count:15,duration:room.duration,mode:room.mode,themeMode:room.theme_mode,
  ...(question?{question:question.question}:{}),...(room.mode==="set"?{setName:room.set_name,items:JSON.parse(room.targets).map((t:Target)=>t.name)}:{})};
 const deck=room.theme_mode==="deck"?{name:room.deck_name,questions:(await all(c,"SELECT question FROM rounds WHERE room_code=? ORDER BY number",code)).map(q=>q.question)}:undefined;
 try{return await createRoom(c,config,code,deck);}catch(error){
  // D1 batch is transactional: the losing concurrent creation leaves no orphan room.
  const winner=await existing();if(winner)return enter(winner.code);throw error;
 }
}
async function feedback(c:Ctx,code:string,body:unknown){
 const {room,member,p}=await membership(c,code);
 const data=z.object({round:z.number().int().min(1).max(15),rating:z.union([z.literal(-1),z.literal(1),z.null()])}).strict().parse(body);
 if(!JSON.parse(room.roster).includes(member.id))throw new GameError(403,"Cet avis est réservé aux participants de la partie.");
 if(data.round>room.current_round||(data.round===room.current_round&&!["reveal","finished"].includes(room.status)))throw new GameError(409,"Donne ton avis après la révélation.");
 const round=await one(c,"SELECT question,skipped FROM rounds WHERE room_code=? AND number=?",code,data.round);
 if(!round?.question||round.skipped)throw new GameError(409,"Cette question n’a pas été jouée.");
 await rate(c,"feedback:"+p.id,30);
 if(data.rating===null)await run(c,"DELETE FROM question_feedback WHERE room_code=? AND round=? AND member_id=?",code,data.round,member.id);
 else await run(c,"INSERT INTO question_feedback(room_code,round,member_id,rating,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(room_code,round,member_id) DO UPDATE SET rating=excluded.rating,updated_at=excluded.updated_at",code,data.round,member.id,data.rating,Date.now());
 return {rating:data.rating};
}
async function join(c:Ctx,code:string){const p=await who(c);await rate(c,"join:"+p!.id,15,60000);if(!/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$/.test(code))throw new GameError(404,"Vérifie le code : cette salle n’est pas disponible.");const existing=await one(c,"SELECT m.state,r.status FROM members m JOIN rooms r ON r.code=m.room_code WHERE m.room_code=? AND m.profile_id=? AND r.expires_at>?",code,p!.id,Date.now());if(existing){if(existing.state==="kicked")throw new GameError(403,"Tu ne peux plus rejoindre cette salle.");if(existing.state==="left"){const back=await run(c,"UPDATE members SET state='joined',last_seen=? WHERE room_code=? AND profile_id=? AND EXISTS(SELECT 1 FROM rooms r WHERE r.code=? AND ((r.status='lobby' AND (SELECT COUNT(*) FROM members m WHERE m.room_code=r.code AND m.state='joined')<12) OR (r.status IN ('voting','choosing','reveal') AND members.id IN (SELECT value FROM json_each(r.roster)))))",Date.now(),code,p!.id,code);if(!back.meta.changes)throw new GameError(409,"Cette salle est pleine ou tu ne fais pas partie des joueurs de cette partie.");}return {code};}
 const r=await run(c,"INSERT INTO members(id,room_code,profile_id,name,name_key,avatar,last_seen,joined_at) SELECT ?,code,?,?,?,?,?,? FROM rooms WHERE code=? AND status='lobby' AND created_at>? AND (SELECT COUNT(*) FROM members WHERE room_code=? AND state='joined')<12",id(),p!.id,p!.name,p!.name.toLocaleLowerCase("fr"),p!.avatar,Date.now(),Date.now(),code,Date.now()-DAY,code);if(!r.meta.changes)throw new GameError(409,"Salle introuvable, pleine ou déjà lancée. Vérifie avec l’hôte.");return {code};}
async function tick(c:Ctx,code:string){await run(c,"UPDATE rooms SET status='reveal' WHERE code=? AND status='voting' AND (deadline<=? OR NOT EXISTS(SELECT 1 FROM members m WHERE m.room_code=rooms.code AND m.state='joined' AND m.id IN (SELECT value FROM json_each(rooms.roster)) AND NOT EXISTS(SELECT 1 FROM ballots b WHERE b.room_code=rooms.code AND b.round=rooms.current_round AND b.member_id=m.id)))",code,Date.now());}
async function snapshot(c:Ctx,code:string):Promise<RoomState>{const {room,member}=await membership(c,code);const ms=await all(c,"SELECT * FROM members WHERE room_code=? AND state!='kicked' ORDER BY joined_at,id",code);const round=await one(c,"SELECT * FROM rounds WHERE room_code=? AND number=?",code,room.current_round);const submitted=await all(c,"SELECT member_id FROM ballots WHERE room_code=? AND round=?",code,room.current_round);const own=await one(c,"SELECT rankings,abstained FROM ballots WHERE room_code=? AND round=? AND member_id=?",code,room.current_round,member.id);
 const feedbackRow=["reveal","finished"].includes(room.status)?await one(c,"SELECT rating FROM question_feedback WHERE room_code=? AND round=? AND member_id=?",code,room.current_round,member.id):null;
 let targets=JSON.parse(room.targets) as Target[];if(room.mode==="players"){const names=new Map(ms.map(m=>[m.id,m]));targets=targets.map(t=>({...t,name:names.get(t.id)?.name??"Joueur supprimé",avatar:names.get(t.id)?.avatar??0}));}
 const visible=["reveal","finished"].includes(room.status);const current=visible&&!round?.skipped?await all(c,"SELECT member_id,rankings,abstained FROM ballots WHERE room_code=? AND round=?",code,room.current_round):[];
 const final=room.status==="finished"?await all(c,"SELECT b.rankings,b.abstained FROM ballots b JOIN rounds r ON r.room_code=b.room_code AND r.number=b.round WHERE b.room_code=? AND r.skipped=0",code):[];
 const reportCount=member.profile_id===room.host_id?(await one(c,"SELECT COUNT(*) AS n FROM question_reports WHERE room_code=? AND round=?",code,room.current_round))!.n:0;
 const ps=room.theme_mode==="box"?await all(c,"SELECT p.id,p.question AS text,m.name AS author FROM proposals p JOIN members m ON m.id=p.member_id WHERE p.room_code=? AND p.round=? ORDER BY p.id",code,Math.max(room.current_round,1)):[];
 return {squad:await squadRoomInfo(room,member),deckName:room.deck_name,visualTheme:room.visual_theme,myQuestionRating:feedbackRow?.rating??null,code,status:room.status,pack:room.pack,roundCount:room.round_count,currentRound:room.current_round,duration:room.duration,mode:room.mode,themeMode:room.theme_mode,setName:room.set_name,me:member.id,hostId:ms.find(m=>m.profile_id===room.host_id)?.id??"",members:ms.map(m=>({id:m.id,name:m.name,avatar:m.avatar,state:m.state,last_seen:m.last_seen,isHost:m.profile_id===room.host_id})),question:round?.question??null,deadline:room.deadline,serverTime:Date.now(),roster:JSON.parse(room.roster),targets,submitted:submitted.map(b=>b.member_id),myBallot:own?JSON.parse(own.rankings):null,myAbstention:!!own?.abstained,revealedBallots:current.map(b=>({memberId:b.member_id,name:ms.find(m=>m.id===b.member_id)?.name??"Joueur supprimé",avatar:ms.find(m=>m.id===b.member_id)?.avatar??0,rankings:JSON.parse(b.rankings),abstained:!!b.abstained})),results:aggregate(targets,current as any),finalResults:aggregate(targets,final as any),skipped:!!round?.skipped,createdAt:room.created_at,reportCount,proposals:ps as any};
}
async function roomAction(c:Ctx,code:string,action:string,body:any){const {p,room,member}=await membership(c,code,true);await rate(c,"action:"+p.id,90);const isHost=p.id===room.host_id;const host=()=>{if(!isHost)throw new GameError(403,"Seul l’hôte peut faire cette action.");};const expected=()=>{if(body.round!==room.current_round)throw new GameError(409,"La manche a changé. Recharge son état.");};
 if(action==="squad-consent"){const agree=z.boolean().parse(body.agree);if(!room.squad_id||room.status!=="finished"||!JSON.parse(room.roster).includes(member.id))throw new GameError(409,"L’accord se donne après la partie.");if(agree&&(!p.account_id||!await squadMembership(room.squad_id,p.id)))throw new GameError(403,"Rejoins la Squad avec ton compte pour partager cette partie.");await run(c,"UPDATE members SET squad_consent=? WHERE id=?",agree?1:0,member.id);return {ok:true};}
 if(action==="pulse"){await run(c,"UPDATE members SET last_seen=? WHERE id=?",Date.now(),member.id);await tick(c,code);return {ok:true};}
 if(action==="start"){host();await requireRoomRights(p.id,room.theme_mode==="pack"?room.pack:"classique",room.visual_theme);const now=Date.now();const nextStatus=room.theme_mode==="box"?"choosing":"voting";const changed=await run(c,"UPDATE rooms SET status=?,current_round=1,deadline=?,roster=(SELECT json_group_array(id) FROM members WHERE room_code=? AND state='joined'),targets=CASE WHEN mode='players' THEN (SELECT json_group_array(json_object('id',id,'name',name,'avatar',avatar)) FROM members WHERE room_code=? AND state='joined') ELSE targets END WHERE code=? AND host_id=? AND status='lobby' AND (SELECT COUNT(*) FROM members WHERE room_code=? AND state='joined')>=3",nextStatus,nextStatus==="voting"?now+room.duration*1000:null,code,code,code,p.id,code);if(!changed.meta.changes)throw new GameError(409,"Il faut au moins 3 joueurs et une salle en attente.");}
 else if(action==="vote"){expected();const data=z.object({round:z.number().int(),rankings:z.record(z.string(),z.number().int().min(0).max(5).nullable()),abstain:z.boolean().default(false)}).strict().parse(body);if(room.status!=="voting"||room.deadline<=Date.now())throw new GameError(409,"Le vote de cette manche est terminé.");if(!JSON.parse(room.roster).includes(member.id))throw new GameError(403,"Tu ne fais pas partie des joueurs de cette manche.");validateBallot(data.rankings,JSON.parse(room.targets),member.id,room.mode,data.abstain);const result=await run(c,"INSERT INTO ballots(room_code,round,member_id,rankings,abstained,submitted_at) SELECT code,current_round,?,?,?,? FROM rooms WHERE code=? AND current_round=? AND status='voting' AND deadline>? AND EXISTS(SELECT 1 FROM members WHERE id=? AND state='joined') ON CONFLICT(room_code,round,member_id) DO NOTHING",member.id,JSON.stringify(data.rankings),data.abstain?1:0,Date.now(),code,data.round,Date.now(),member.id);if(!result.meta.changes)throw new GameError(409,"Ton vote est déjà enregistré ou la manche est terminée.");await tick(c,code);}
 else if(action==="next"){host();expected();const finished=room.current_round>=room.round_count;const status=finished?"finished":room.theme_mode==="box"?"choosing":"voting";const res=await run(c,"UPDATE rooms SET status=?,current_round=current_round+?,deadline=?,finished_at=? WHERE code=? AND host_id=? AND status='reveal' AND current_round=?",status,finished?0:1,status==="voting"?Date.now()+room.duration*1000:null,finished?Date.now():null,code,p.id,body.round);if(!res.meta.changes)throw new GameError(409,"Attends les résultats avant de passer à la suite.");}
 else if(action==="skip"){host();expected();await c.db.batch([stmt(c,"UPDATE rounds SET skipped=1 WHERE room_code=? AND number=? AND EXISTS(SELECT 1 FROM rooms WHERE code=? AND host_id=? AND status IN ('voting','choosing') AND current_round=?)",code,body.round,code,p.id,body.round),stmt(c,"UPDATE rooms SET status='reveal' WHERE code=? AND host_id=? AND current_round=? AND status IN ('voting','choosing')",code,p.id,body.round)]);}
 else if(action==="choose"){host();expected();const text=questionSchema.parse(body.question);await c.db.batch([stmt(c,"UPDATE rounds SET question=? WHERE room_code=? AND number=? AND EXISTS(SELECT 1 FROM rooms WHERE code=? AND host_id=? AND current_round=? AND status='choosing')",text,code,body.round,code,p.id,body.round),stmt(c,"UPDATE rooms SET status='voting',deadline=? WHERE code=? AND host_id=? AND current_round=? AND status='choosing'",Date.now()+room.duration*1000,code,p.id,body.round)]);}
 else if(action==="propose"){const text=questionSchema.parse(body.question);const round=Math.max(1,room.current_round);if(room.theme_mode!=="box"||!["lobby","choosing"].includes(room.status))throw new GameError(409,"Les propositions sont fermées pour cette manche.");await run(c,"INSERT INTO proposals(id,room_code,round,member_id,question) SELECT ?,code,?,?,? FROM rooms WHERE code=? AND status IN ('lobby','choosing') AND current_round=? ON CONFLICT(room_code,round,member_id) DO UPDATE SET question=excluded.question",id(),round,member.id,text,code,room.current_round);}
 else if(action==="kick"){host();const target=z.string().uuid().parse(body.memberId);if(target===member.id)throw new GameError(400,"Utilise Quitter la salle.");const result=await run(c,"UPDATE members SET state='kicked' WHERE room_code=? AND id=? AND EXISTS(SELECT 1 FROM rooms WHERE code=? AND host_id=? AND status='lobby')",code,target,code,p.id);if(!result.meta.changes)throw new GameError(409,"L’exclusion est disponible avant le début de la partie.");}
 else if(action==="leave"){await c.db.batch([stmt(c,"UPDATE members SET state='left' WHERE id=?",member.id),stmt(c,"UPDATE rooms SET host_id=COALESCE((SELECT profile_id FROM members WHERE room_code=? AND state='joined' AND profile_id IS NOT NULL ORDER BY joined_at LIMIT 1),host_id),status=CASE WHEN NOT EXISTS(SELECT 1 FROM members WHERE room_code=? AND state='joined') AND status NOT IN ('finished','closed') THEN 'closed' ELSE status END WHERE code=? AND host_id=?",code,code,code,p.id)]);await tick(c,code);return {ok:true};}
 else if(action==="claim-host"){if(isHost)return {ok:true};const r=await run(c,"UPDATE rooms SET host_id=? WHERE code=? AND status NOT IN ('finished','closed') AND EXISTS(SELECT 1 FROM members WHERE room_code=? AND profile_id=rooms.host_id AND (last_seen<? OR state!='joined'))",p.id,code,code,Date.now()-90000);if(!r.meta.changes)throw new GameError(409,"L’hôte est encore connecté. Attends 90 secondes après sa dernière présence.");}
 else if(action==="report"){expected();const reason=z.enum(["inapproprie","personnel","autre"]).parse(body.reason);await run(c,"INSERT INTO question_reports(id,room_code,round,member_id,reason,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT(room_code,round,member_id) DO NOTHING",id(),code,room.current_round,member.id,reason,Date.now());return {ok:true};}
 else throw new GameError(404,"Action introuvable.");return {ok:true};
}
async function stats(c:Ctx){const p=await requireAccount(c);const result=await playerStats(c.db,p.id);const access=await rights(p.id);return {profile:person(p),...result,progress:{xp:result.games*100+result.roundVotes*10,level:1+Math.floor((result.games*100+result.roundVotes*10)/500)},advanced:access.plus?{months:Object.values(result.history.reduce((a:Record<string,any>,g:any)=>{const key=new Date(g.finished_at).toISOString().slice(0,7);a[key]??={month:key,games:0,votes:0};a[key].games++;a[key].votes+=Number(g.roundVotes);return a;},{})).sort((a:any,b:any)=>a.month.localeCompare(b.month)),packs:PACKS.map(pack=>({name:pack.name,games:result.history.filter(g=>g.pack===pack.id).length})).filter(p=>p.games>0)}:null};}
async function accountDelete(c:Ctx,password:unknown){const p=await requireAccount(c);if(p.role==="owner")throw new GameError(409,"Le compte propriétaire doit être transféré avant sa suppression.");await requirePassword(c.request,password);if(await one(c,"SELECT id FROM squads WHERE owner_id=?",p.id))throw new GameError(409,"Transfère ou supprime tes Squads avant de supprimer ton compte.");await cancelAccountSubscriptions(p.id);await c.db.batch([
 stmt(c,"UPDATE rooms SET status='closed' WHERE host_id=? AND status NOT IN ('finished','closed')",p.id),
 stmt(c,"UPDATE rooms SET targets=(SELECT json_group_array(CASE WHEN json_extract(j.value,'$.id') IN (SELECT id FROM members WHERE profile_id=?) THEN json_set(j.value,'$.name','Joueur supprimé','$.avatar',0) ELSE json(j.value) END) FROM json_each(rooms.targets) j) WHERE mode='players' AND code IN (SELECT room_code FROM members WHERE profile_id=?)",p.id,p.id),
 stmt(c,"UPDATE members SET name='Joueur supprimé',name_key=id,avatar=0,state=CASE WHEN state='joined' THEN 'left' ELSE state END WHERE profile_id=?",p.id),
 stmt(c,"DELETE FROM proposals WHERE member_id IN (SELECT id FROM members WHERE profile_id=?)",p.id),
 stmt(c,"DELETE FROM question_reports WHERE member_id IN (SELECT id FROM members WHERE profile_id=?)",p.id),
 stmt(c,"DELETE FROM question_feedback WHERE member_id IN (SELECT id FROM members WHERE profile_id=?)",p.id),
 stmt(c,"UPDATE rooms SET host_id='' WHERE host_id=?",p.id),
 stmt(c,"DELETE FROM profiles WHERE id=?",p.id),
 stmt(c,"DELETE FROM auth_user WHERE id=?",p.account_id)
 ]);c.setCookie=cookieName(c.request)+"=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"+(new URL(c.request.url).protocol==="https:"?"; Secure":"");return {ok:true};}
export async function handleApi(request:Request,segments:string[]):Promise<Response>{if(segments[0]==="squads")return squadsRoute(request,segments.slice(1));if(segments[0]==="decks")return decksRoute(request,segments.slice(1));if(segments[0]==="billing")return billingRoute(request,segments.slice(1));if(segments[0]==="auth")return authRoute(request,segments.slice(1).join("/"));if(segments[0]==="admin")return adminRoute(request,segments.slice(1));let c:Ctx|undefined;try{c={request,db:database()};const path=segments.join("/");const method=request.method;let body:any={};if(method!=="GET"){guard(c);const ip=request.headers.get("cf-connecting-ip")??"local";await rate(c,"ip:"+await hash(ip),180);if(path==="profile")await rate(c,"profile-ip:"+await hash(ip),20,600000);body=await readBody(c);}
 let result:unknown;
 if(path==="me"&&method==="GET"){const auth=await identity(c.request);const p=await who(c,false);result={separatePlayer:!!sessionScope(c.request),signedIn:!!auth,profile:p?person(p):null,email:auth?.email??null,emailVerified:auth?.emailVerified??false,activeRooms:p?await all(c,"SELECT r.code,r.status FROM rooms r JOIN members m ON m.room_code=r.code WHERE m.profile_id=? AND m.state='joined' AND r.status NOT IN ('finished','closed') AND r.created_at>? ORDER BY r.created_at DESC LIMIT 5",p.id,Date.now()-DAY):[]};}
 else if(path==="profile"&&method==="POST")result=await profile(c,body);
 else if(path==="rooms"&&method==="POST")result=await createRoom(c,body);
 else if(segments[0]==="rooms"&&segments.length===2&&method==="GET")result=await snapshot(c,segments[1]);
 else if(segments[0]==="rooms"&&segments.length===3&&method==="POST")result=segments[2]==="join"?await join(c,segments[1]):segments[2]==="rematch"?await rematch(c,segments[1]):segments[2]==="feedback"?await feedback(c,segments[1],body):await roomAction(c,segments[1],segments[2],body);
 else if(path==="stats"&&method==="GET")result=await stats(c);
 else if(path==="sets"&&method==="GET"){const p=await requireAccount(c);result={sets:(await all(c,"SELECT id,name,items FROM saved_sets WHERE owner_id=? ORDER BY updated_at DESC LIMIT 50",p.id)).map(s=>({...s,items:JSON.parse(s.items)}))};}
 else if(path==="sets"&&method==="POST"){const p=await requireAccount(c);const data=z.object({id:z.string().uuid().optional(),name:nameSchema,items:itemsSchema}).strict().parse(body);if(data.id){const r=await run(c,"UPDATE saved_sets SET name=?,items=?,updated_at=? WHERE id=? AND owner_id=?",data.name,JSON.stringify(data.items),Date.now(),data.id,p.id);if(!r.meta.changes)throw new GameError(404,"Set introuvable.");}else{const n=await one(c,"SELECT COUNT(*) AS n FROM saved_sets WHERE owner_id=?",p.id);if(n!.n>=50)throw new GameError(409,"La limite de 50 sets est atteinte.");await run(c,"INSERT INTO saved_sets(id,owner_id,name,items,updated_at) VALUES(?,?,?,?,?)",id(),p.id,data.name,JSON.stringify(data.items),Date.now());}result={ok:true};}
 else if(segments[0]==="sets"&&segments.length===2&&method==="DELETE"){const p=await requireAccount(c);await run(c,"DELETE FROM saved_sets WHERE id=? AND owner_id=?",segments[1],p.id);result={ok:true};}
 else if(path==="account/export"&&method==="GET"){const p=await requireAccount(c);const membership=await all(c,"SELECT id,room_code,name,avatar,state,joined_at FROM members WHERE profile_id=?",p.id);const votes=await all(c,"SELECT b.room_code,b.round,b.rankings,b.abstained,b.submitted_at FROM ballots b JOIN members m ON m.id=b.member_id WHERE m.profile_id=?",p.id);const sets=await all(c,"SELECT name,items,updated_at FROM saved_sets WHERE owner_id=?",p.id);const questionFeedback=await all(c,"SELECT f.room_code,f.round,f.rating,f.updated_at FROM question_feedback f JOIN members m ON m.id=f.member_id WHERE m.profile_id=?",p.id);result={decks:await all(c,"SELECT id,name,questions,updated_at FROM question_decks WHERE owner_id=?",p.id),squads:await all(c,"SELECT s.id,s.name,sm.state,sm.joined_at FROM squad_members sm JOIN squads s ON s.id=sm.squad_id WHERE sm.profile_id=?",p.id),billing:await billingStatus(p.id),questionFeedback,exportedAt:new Date().toISOString(),profile:person(p),email:(await identity(c.request))?.email,memberships:membership,votes,sets};}
 else if(path==="account"&&method==="DELETE"){if(body.confirmation!=="SUPPRIMER")throw new GameError(400,"La confirmation est nécessaire.");const p=await requireAccount(c);result=await withLock("billing:"+p.id,()=>accountDelete(c!,body.password));}
 else throw new GameError(404,"Ressource introuvable.");
 const headers:Record<string,string>={"Cache-Control":"no-store, private","X-Content-Type-Options":"nosniff"};if(c.setCookie)headers["Set-Cookie"]=c.setCookie;return Response.json(result,{headers});
 }catch(error){let status=503,message="Le service est momentanément indisponible. Tes saisies sont conservées : réessaie.";if(error instanceof GameError){status=error.status;message=error.message;}else if(error instanceof z.ZodError){status=400;message=error.issues[0]?.message??"Vérifie les champs.";}else if(error instanceof Error&&error.message.includes("UNIQUE constraint failed: members.room_code, members.name_key")){status=409;message="Ce pseudo est déjà utilisé dans la salle. Choisis-en un autre dans ton profil.";}else console.error("CKK API failure",request.method,segments.slice(0,1).join("/"),error instanceof Error?error.name:"Unknown");return Response.json({error:message},{status,headers:{"Cache-Control":"no-store, private","X-Content-Type-Options":"nosniff",...(status===429?{"Retry-After":"60"}:{})}});}
}
